/**
 * The bundled station list — a small, offline-capable fallback for stop search.
 *
 * Live search through `/stop_finder` is the primary path: it covers every stop,
 * wharf, interchange and address on the network and never goes stale. This list
 * exists for the cases where that cannot answer:
 *
 *  - the device is offline or the API is unreachable
 *  - the query is shorter than the live search's minimum
 *  - the API key is missing, so the app is still usable for browsing
 *
 * It is generated by `npm run data:stations` from the vendored TfNSW dataset,
 * projected down to the fields the UI needs (33 KB rather than 291 KB). Since
 * it is a frozen snapshot, treat it as a convenience rather than a source of
 * truth — anything the live search returns wins.
 */

import type { Mode, StopSuggestion } from './types';
import stationsData from './stations.json';

export interface Station {
    /** TSN, e.g. `200060` for Central. Valid as a trip origin or destination. */
    id: string;
    name: string;
    /** True when the station is on the Metro network. */
    metro: boolean;
    lat: number;
    lon: number;
}

export const STATIONS: Station[] = stationsData as Station[];

function modesOf(station: Station): Mode[] {
    return station.metro ? ['train', 'metro'] : ['train'];
}

/**
 * Filters the bundled list by name.
 *
 * Ranks a prefix match above a match anywhere in the name, so typing "central"
 * offers Central Station before Central Coast stations. `matchQuality` uses the
 * same scale as the live search so the two can be presented identically.
 */
export function searchStations(query: string, limit = 12): StopSuggestion[] {
    const needle = query.trim().toLowerCase();
    if (!needle) {
        return [];
    }
    const matches: { station: Station; quality: number }[] = [];
    for (const station of STATIONS) {
        const name = station.name.toLowerCase();
        if (name.startsWith(needle)) {
            matches.push({ station: station, quality: 900 });
        } else if (name.includes(needle)) {
            matches.push({ station: station, quality: 500 });
        }
    }
    return matches
        .sort(
            (a, b) =>
                b.quality - a.quality || a.station.name.localeCompare(b.station.name)
        )
        .slice(0, limit)
        .map(({ station, quality }) => ({
            id: station.id,
            name: station.name,
            modes: modesOf(station),
            matchQuality: quality,
        }));
}

/** Looks up a station name by id, for labelling a trip from its URL. */
export function stationNameById(id: string | null | undefined): string | null {
    if (!id) {
        return null;
    }
    return STATIONS.find((station) => station.id === id)?.name ?? null;
}
